
name: Generate Docs

on:
  push:
    paths:
      - '**'
      - '!docs/**'
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Set up Python (or any other required setup depending on your generate.py script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Generate documentation
        run: python ./generate.py
      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "nacitar.sevaht@gmail.com" # replace with your email or a dedicated bot email
          git add docs/
          git diff-index --quiet HEAD || git commit -m "Update generated pages via GitHub Actions"
          git push
